### ISSUE TITLE
why do we need scale the output by 400/10?

### ISSUE THREAD

**Issue by hsliuustc** [vc-bonn/Unsupervised_Deep_Learning_of_Incompressible_Fluid_Dynamics#3]
https://github.com/aschethor/Unsupervised_Deep_Learning_of_Incompressible_Fluid_Dynamics/blob/89bed1865cb83461de8682bd22614264f2d06b99/pde_cnn.py#L49

**Comment by wandeln** [comment]
Hi, thanks for your question!
We bound the vector potential and pressure fields in between [-400,400] and [-10,10] respectively in order to avoid filling the training pool with highly diverged data at the beginning of training, when the fluid models are still unstable.
I hope this answers your question :)
Let me know, if there are further questions / remarks!
Best regards, Nils

**Comment by hsliuustc** [comment]
I see.
I notice your group has another paper called Spline-PINN under AAAI review. It seems that method should be able to achieve higher acc since it utilizes the exact PINN loss rather than by finite-difference. I can't wait to try it once you opensource the codes for it.

**Comment by wandeln** [comment]
Yes indeed, we're currently awaiting the final decision for our Spline-PINN paper from AAAI.
We hope, our submission gets accepted so we can release the code as well as some pretrained models :)
Best, Nils
